# Sponsor button shown on the repo.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom: ["https://www.keeplas.com/pricing"]
