const $=s=>document.querySelector(s), S=window.KEEPLAS_SCREENS;let lang='fr',device='mobile',theme='light',current='home',recording=false;const T=(en,fr)=>lang==='fr'?fr:en;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const icon=k=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${KEEPLAS_ICONS[k]||KEEPLAS_ICONS.file}"/></svg>`;const brand=`<span class="brand"><img class="logo" src="../assets/logo/logo.svg" alt="Keeplas">Keeplas</span>`;const hero=`<img class="hero" src="../assets/illustrations/landscape.svg" alt="">`;
function toast(s){let old=$('.toast');if(old)old.remove();let el=document.createElement('div');el.className='toast';el.role='status';el.textContent=s;document.body.append(el);setTimeout(()=>el.remove(),3500)}
function go(id){if(!S.some(x=>x.id===id))id='home';current=id;location.hash=id;recording=false;render()}
function progress(s){if(s.category!=='Setup')return '';let n=({setup:0,verify:0,passkey:1,'create-vault':2,optional:3,complete:3})[s.id];return `<div class="card"><b>${T('Required steps','Étapes obligatoires')} · ${n}/3</b><div class="steps">${[T('Verify phone','Vérifier le numéro'),T('Create passkey','Créer une passkey'),T('Create vault','Créer le coffre')].map((a,i)=>`<span><b>${i<n?'✓':i+1}</b>${a}</span>`).join('')}</div>${n===3?T('Optional protection · 0/2','Protection facultative · 0/2'):''}</div>`}
function extras(s){let id=s.id;let phone=`<label>${T('Phone number','Numéro de téléphone')}<input type="tel" autocomplete="tel" placeholder="+254 712 345 678"></label>`;
if(id==='setup')return phone;
if(id==='verify')return `<label>${T('Verification code','Code de vérification')}<input inputmode="numeric" maxlength="6" placeholder="000000"></label>`;
if(id==='signin'||id==='recovery')return phone;
if(id==='unlock')return `<div class="preview">${icon('key')} ${T('Device authentication','Authentification de l’appareil')}</div><label>${T('Optional PIN after biometrics','PIN facultatif après biométrie')}<input type="password" inputmode="numeric" placeholder="••••••"></label>`;
if(id==='add-person')return `<label>${T('Name','Nom')}<input placeholder="Marie"></label>${phone}<label class="check"><input type="checkbox" checked>${T('Trust contact — no file access','Contact de confiance — aucun accès aux fichiers')}</label><label class="check"><input type="checkbox">${T('Beneficiary — assigned content only','Bénéficiaire — contenu attribué uniquement')}</label>`;
if(id==='share')return `<label>${T('Folder','Dossier')}<select><option>${T('Family documents','Documents de famille')}</option></select></label><label>${T('Person','Personne')}<select><option>Marie</option><option>Paul</option></select></label><label class="check"><input type="radio" name="timing" checked>${T('Now','Maintenant')}</label><label class="check"><input type="radio" name="timing">${T('After 2 confirmations + 72-hour grace period','Après 2 confirmations + délai de grâce de 72 h')}</label>`;
if(id==='note')return `<label>${T('Title','Titre')}<input placeholder="${T('Instructions','Instructions')}"></label><label>${T('Note','Note')}<textarea rows="6"></textarea></label>`;
if(id==='review')return `<div class="preview">${icon('video')} ${T('Recording preview (demo)','Aperçu de l’enregistrement (démo)')}</div><label>${T('Title','Titre')}<input value="${T('Account instructions','Instructions du compte')}"></label>`;
if(id==='video'||id==='audio')return `<div class="preview" id="record-preview">${icon(id==='video'?'camera':'mic')}<b>${T('Ready to record','Prêt à enregistrer')}</b></div>`;
if(id==='scan'||id==='qr-scan')return `<div class="preview" style="height:280px">${icon('camera')} ${T('Camera preview · demo','Aperçu caméra · démo')}</div>`;
if(id==='screen-record')return `<div class="stack">${['Browser tab|Onglet','Window|Fenêtre','Entire screen|Écran entier'].map((p,i)=>`<button class="choice ${i===0?'selected':''}" data-choice>${icon('monitor')}${T(...p.split('|'))}</button>`).join('')}</div><label class="check"><input type="checkbox">${T('Microphone (optional)','Microphone (facultatif)')}</label>`;
if(id==='web-qr')return `<div class="card row">${icon('qr')}<b>QR · ${T('Visual placeholder','Repère visuel')}</b></div><p class="muted">${T('No functional sign-in QR is generated in this prototype.','Ce prototype ne génère pas de QR de connexion fonctionnel.')}</p><label class="check"><input type="checkbox">${T('Trust this browser','Faire confiance à ce navigateur')}</label>`;
if(id==='recovery-pending'||id==='recovery-approve')return `<div class="note"><b>${T('Recovery code','Code de récupération')} · 4729</b></div>${id==='recovery-pending'?'<progress value="1" max="2"></progress>':`<label class="check"><input type="checkbox" id="verified">${T('I verified Alex and the code by phone/video','J’ai vérifié Alex et le code par téléphone/vidéo')}</label>`}`;
if(id==='security')return `<label class="check"><input type="checkbox">${T('Require Keeplas PIN after biometrics','Exiger un PIN Keeplas après biométrie')}</label>`;
if(id==='kit')return `<div class="note warning">${T('Demo only: no secret phrase is generated or exported.','Démo uniquement : aucune phrase secrète n’est générée ou exportée.')}</div>`;
return ''}
function render(){document.documentElement.dataset.theme=theme;let s=S.find(x=>x.id===current)||S[0];$('#catalog').innerHTML=S.map(x=>`<button class="${x.id===current?'active':''}" data-go="${x.id}">${esc(T(x.en,x.fr))}</button>`).join('');$('#page-title').textContent=T(s.en,s.fr);let items=s.items.map(x=>`<${x[3]?'button':'div'} class="${x[3]?'choice':'list-item'}" ${x[3]?`data-go="${x[3]}"`:''}>${icon(x[0])}<span class="grow">${esc(T(x[1],x[2]))}</span></${x[3]?'button':'div'}>`).join('');let actions=s.actions.map((a,i)=>`<button data-action="${a[2]}" class="${/Revoke|Reject|wasn/.test(a[0])?'danger':i?'secondary':''}">${esc(T(a[0],a[1]))}</button>`).join('');let content=`<div class="content"><span class="badge">${esc(s.category)} · ${esc(s.id)}</span><h1>${esc(T(s.en,s.fr))}</h1><p class="muted">${esc(T(s.body,s.bfr))}</p>${['welcome','home','life-check','restored','succession'].includes(s.id)?hero:''}${progress(s)}${extras(s)}<div class="stack">${items}</div><div class="actions">${actions}</div></div>`;let nav=`<nav class="nav">${[['home','home','Home','Accueil'],['search','home','Search','Recherche'],['plus','capture','Add','Ajouter'],['people','people','People','Contacts'],['settings','security','Settings','Paramètres']].map(([ic,id,en,fr])=>`<a href="#${id}" data-go="${id}">${icon(ic)}${T(en,fr)}</a>`).join('')}</nav>`;let sidebar=`<aside class="sidebar">${brand}${[['home','My vault','Mon coffre'],['shared','Shared with me','Partagé avec moi'],['people','People','Contacts'],['capture','Add item','Ajouter'],['devices','Devices','Appareils'],['recovery','Recovery','Récupération'],['life-check','Life check','Vérification de vie'],['security','Settings','Paramètres']].map(([id,en,fr])=>`<a href="#${id}" data-go="${id}">${T(en,fr)}</a>`).join('')}</aside>`;$('#screen').className='screen '+device;$('#screen').innerHTML=device==='mobile'?`<header class="header">${brand}<small>${lang.toUpperCase()}</small></header>${content}${nav}`:`${sidebar}<div><header class="header">${brand}<small>${lang.toUpperCase()}</small></header>${content}</div>`;$('#caption').textContent=T('Prototype only. Authentication, encryption, recording, sharing and notifications are simulated. No data is sent.','Prototype uniquement. Authentification, chiffrement, enregistrement, partage et notifications sont simulés. Aucune donnée n’est envoyée.');document.querySelectorAll('[data-go]').forEach(el=>el.onclick=e=>{e.preventDefault();go(el.dataset.go)});document.querySelectorAll('[data-choice]').forEach(el=>el.onclick=()=>{document.querySelectorAll('[data-choice]').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')});document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>act(el.dataset.action));}
function act(id){if(id==='record'){recording=!recording;$('#record-preview').innerHTML=`${icon('mic')}<b>${recording?T('● Recording · 00:24','● Enregistrement · 00:24'):T('Stopped','Arrêté')}</b>`;return}if(current==='recovery-approve'&&id==='restored'&&!$('#verified').checked){toast(T('Confirm identity verification first.','Confirmez d’abord la vérification d’identité.'));return}if(id==='demo'){toast(T('Demonstration only — no external action.','Démonstration uniquement — aucune action externe.'));return}if(id==='checkin'){toast(T('Check-in completed (demo).','Vérification de vie terminée (démo).'));return}if(id==='revoke'){if(confirm(T('Revoke this device? (demo)','Révoquer cet appareil ? (démo)'))){toast(T('Device revoked (demo).','Appareil révoqué (démo).'));go('devices')}return}go(id)}
$('#language').onchange=e=>{lang=e.target.value;render()};$('#device').onchange=e=>{device=e.target.value;render()};$('#theme').onchange=e=>{theme=e.target.value;render()};window.onhashchange=()=>{current=location.hash.slice(1)||'home';render()};current=location.hash.slice(1)||'home';render();
