/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecurityIndexRouteImport } from './routes/security/index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as LoginTotpIndexRouteImport } from './routes/login/totp/index'
import { Route as LoginRecoveryIndexRouteImport } from './routes/login/recovery/index'
import { Route as LoginOtpIndexRouteImport } from './routes/login/otp/index'
import { Route as LifeCheckConfirmIndexRouteImport } from './routes/life-check/confirm/index'
import { Route as InviteTokenIndexRouteImport } from './routes/invite/$token/index'
import { Route as OnboardingOnboardingIndexRouteImport } from './routes/_onboarding/onboarding/index'
import { Route as DashboardVaultIndexRouteImport } from './routes/_dashboard/vault/index'
import { Route as DashboardTrustedContactsIndexRouteImport } from './routes/_dashboard/trusted-contacts/index'
import { Route as DashboardTerminateIndexRouteImport } from './routes/_dashboard/terminate/index'
import { Route as DashboardSharedWithMeIndexRouteImport } from './routes/_dashboard/shared-with-me/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardLifeCheckIndexRouteImport } from './routes/_dashboard/life-check/index'
import { Route as DashboardHubIndexRouteImport } from './routes/_dashboard/hub/index'
import { Route as DashboardDocsIndexRouteImport } from './routes/_dashboard/docs/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as LoginTotpRecoveryIndexRouteImport } from './routes/login/totp/recovery/index'
import { Route as LoginOtpRecoveryIndexRouteImport } from './routes/login/otp/recovery/index'
import { Route as DashboardVaultItemIdIndexRouteImport } from './routes/_dashboard/vault/$itemId/index'
import { Route as DashboardSettingsUsageIndexRouteImport } from './routes/_dashboard/settings/usage/index'
import { Route as DashboardSettingsSubscriptionIndexRouteImport } from './routes/_dashboard/settings/subscription/index'
import { Route as DashboardSettingsSecurityIndexRouteImport } from './routes/_dashboard/settings/security/index'
import { Route as DashboardSettingsRecoveryKitIndexRouteImport } from './routes/_dashboard/settings/recovery-kit/index'
import { Route as DashboardSettingsPreferencesIndexRouteImport } from './routes/_dashboard/settings/preferences/index'
import { Route as DashboardSettingsContinuityIndexRouteImport } from './routes/_dashboard/settings/continuity/index'
import { Route as DashboardSettingsContactIndexRouteImport } from './routes/_dashboard/settings/contact/index'
import { Route as DashboardDocsVaultIndexRouteImport } from './routes/_dashboard/docs/vault/index'
import { Route as DashboardDocsTrustedContactsIndexRouteImport } from './routes/_dashboard/docs/trusted-contacts/index'
import { Route as DashboardDocsRecoveryIndexRouteImport } from './routes/_dashboard/docs/recovery/index'
import { Route as DashboardDocsLifeCheckIndexRouteImport } from './routes/_dashboard/docs/life-check/index'
import { Route as DashboardDocsLettersIndexRouteImport } from './routes/_dashboard/docs/letters/index'
import { Route as DashboardDocsInsightsIndexRouteImport } from './routes/_dashboard/docs/insights/index'
import { Route as DashboardDocsEmergencyInfoIndexRouteImport } from './routes/_dashboard/docs/emergency-info/index'
import { Route as DashboardSharedWithMeContactIdMemorialIndexRouteImport } from './routes/_dashboard/shared-with-me/$contactId/memorial/index'
import { Route as DashboardSharedWithMeContactIdMemorialItemIdIndexRouteImport } from './routes/_dashboard/shared-with-me/$contactId/memorial/$itemId/index'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const LoginTotpIndexRoute = LoginTotpIndexRouteImport.update({
  id: '/login/totp/',
  path: '/login/totp/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRecoveryIndexRoute = LoginRecoveryIndexRouteImport.update({
  id: '/login/recovery/',
  path: '/login/recovery/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOtpIndexRoute = LoginOtpIndexRouteImport.update({
  id: '/login/otp/',
  path: '/login/otp/',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeCheckConfirmIndexRoute = LifeCheckConfirmIndexRouteImport.update({
  id: '/life-check/confirm/',
  path: '/life-check/confirm/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenIndexRoute = InviteTokenIndexRouteImport.update({
  id: '/invite/$token/',
  path: '/invite/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOnboardingIndexRoute =
  OnboardingOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => OnboardingRoute,
  } as any)
const DashboardVaultIndexRoute = DashboardVaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrustedContactsIndexRoute =
  DashboardTrustedContactsIndexRouteImport.update({
    id: '/trusted-contacts/',
    path: '/trusted-contacts/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTerminateIndexRoute = DashboardTerminateIndexRouteImport.update({
  id: '/terminate/',
  path: '/terminate/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSharedWithMeIndexRoute =
  DashboardSharedWithMeIndexRouteImport.update({
    id: '/shared-with-me/',
    path: '/shared-with-me/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardLifeCheckIndexRoute = DashboardLifeCheckIndexRouteImport.update({
  id: '/life-check/',
  path: '/life-check/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHubIndexRoute = DashboardHubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsIndexRoute = DashboardDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const LoginTotpRecoveryIndexRoute = LoginTotpRecoveryIndexRouteImport.update({
  id: '/login/totp/recovery/',
  path: '/login/totp/recovery/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOtpRecoveryIndexRoute = LoginOtpRecoveryIndexRouteImport.update({
  id: '/login/otp/recovery/',
  path: '/login/otp/recovery/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVaultItemIdIndexRoute =
  DashboardVaultItemIdIndexRouteImport.update({
    id: '/vault/$itemId/',
    path: '/vault/$itemId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsUsageIndexRoute =
  DashboardSettingsUsageIndexRouteImport.update({
    id: '/usage/',
    path: '/usage/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsSubscriptionIndexRoute =
  DashboardSettingsSubscriptionIndexRouteImport.update({
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsSecurityIndexRoute =
  DashboardSettingsSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsRecoveryKitIndexRoute =
  DashboardSettingsRecoveryKitIndexRouteImport.update({
    id: '/recovery-kit/',
    path: '/recovery-kit/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsPreferencesIndexRoute =
  DashboardSettingsPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsContinuityIndexRoute =
  DashboardSettingsContinuityIndexRouteImport.update({
    id: '/continuity/',
    path: '/continuity/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsContactIndexRoute =
  DashboardSettingsContactIndexRouteImport.update({
    id: '/contact/',
    path: '/contact/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardDocsVaultIndexRoute = DashboardDocsVaultIndexRouteImport.update({
  id: '/docs/vault/',
  path: '/docs/vault/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsTrustedContactsIndexRoute =
  DashboardDocsTrustedContactsIndexRouteImport.update({
    id: '/docs/trusted-contacts/',
    path: '/docs/trusted-contacts/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocsRecoveryIndexRoute =
  DashboardDocsRecoveryIndexRouteImport.update({
    id: '/docs/recovery/',
    path: '/docs/recovery/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocsLifeCheckIndexRoute =
  DashboardDocsLifeCheckIndexRouteImport.update({
    id: '/docs/life-check/',
    path: '/docs/life-check/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocsLettersIndexRoute =
  DashboardDocsLettersIndexRouteImport.update({
    id: '/docs/letters/',
    path: '/docs/letters/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocsInsightsIndexRoute =
  DashboardDocsInsightsIndexRouteImport.update({
    id: '/docs/insights/',
    path: '/docs/insights/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocsEmergencyInfoIndexRoute =
  DashboardDocsEmergencyInfoIndexRouteImport.update({
    id: '/docs/emergency-info/',
    path: '/docs/emergency-info/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSharedWithMeContactIdMemorialIndexRoute =
  DashboardSharedWithMeContactIdMemorialIndexRouteImport.update({
    id: '/shared-with-me/$contactId/memorial/',
    path: '/shared-with-me/$contactId/memorial/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSharedWithMeContactIdMemorialItemIdIndexRoute =
  DashboardSharedWithMeContactIdMemorialItemIdIndexRouteImport.update({
    id: '/shared-with-me/$contactId/memorial/$itemId/',
    path: '/shared-with-me/$contactId/memorial/$itemId/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof DashboardSettingsRouteWithChildren
  '/security/': typeof SecurityIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/docs/': typeof DashboardDocsIndexRoute
  '/hub/': typeof DashboardHubIndexRoute
  '/life-check/': typeof DashboardLifeCheckIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/shared-with-me/': typeof DashboardSharedWithMeIndexRoute
  '/terminate/': typeof DashboardTerminateIndexRoute
  '/trusted-contacts/': typeof DashboardTrustedContactsIndexRoute
  '/vault/': typeof DashboardVaultIndexRoute
  '/onboarding/': typeof OnboardingOnboardingIndexRoute
  '/invite/$token/': typeof InviteTokenIndexRoute
  '/life-check/confirm/': typeof LifeCheckConfirmIndexRoute
  '/login/otp/': typeof LoginOtpIndexRoute
  '/login/recovery/': typeof LoginRecoveryIndexRoute
  '/login/totp/': typeof LoginTotpIndexRoute
  '/docs/emergency-info/': typeof DashboardDocsEmergencyInfoIndexRoute
  '/docs/insights/': typeof DashboardDocsInsightsIndexRoute
  '/docs/letters/': typeof DashboardDocsLettersIndexRoute
  '/docs/life-check/': typeof DashboardDocsLifeCheckIndexRoute
  '/docs/recovery/': typeof DashboardDocsRecoveryIndexRoute
  '/docs/trusted-contacts/': typeof DashboardDocsTrustedContactsIndexRoute
  '/docs/vault/': typeof DashboardDocsVaultIndexRoute
  '/settings/contact/': typeof DashboardSettingsContactIndexRoute
  '/settings/continuity/': typeof DashboardSettingsContinuityIndexRoute
  '/settings/preferences/': typeof DashboardSettingsPreferencesIndexRoute
  '/settings/recovery-kit/': typeof DashboardSettingsRecoveryKitIndexRoute
  '/settings/security/': typeof DashboardSettingsSecurityIndexRoute
  '/settings/subscription/': typeof DashboardSettingsSubscriptionIndexRoute
  '/settings/usage/': typeof DashboardSettingsUsageIndexRoute
  '/vault/$itemId/': typeof DashboardVaultItemIdIndexRoute
  '/login/otp/recovery/': typeof LoginOtpRecoveryIndexRoute
  '/login/totp/recovery/': typeof LoginTotpRecoveryIndexRoute
  '/shared-with-me/$contactId/memorial/': typeof DashboardSharedWithMeContactIdMemorialIndexRoute
  '/shared-with-me/$contactId/memorial/$itemId/': typeof DashboardSharedWithMeContactIdMemorialItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/security': typeof SecurityIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/docs': typeof DashboardDocsIndexRoute
  '/hub': typeof DashboardHubIndexRoute
  '/life-check': typeof DashboardLifeCheckIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/shared-with-me': typeof DashboardSharedWithMeIndexRoute
  '/terminate': typeof DashboardTerminateIndexRoute
  '/trusted-contacts': typeof DashboardTrustedContactsIndexRoute
  '/vault': typeof DashboardVaultIndexRoute
  '/onboarding': typeof OnboardingOnboardingIndexRoute
  '/invite/$token': typeof InviteTokenIndexRoute
  '/life-check/confirm': typeof LifeCheckConfirmIndexRoute
  '/login/otp': typeof LoginOtpIndexRoute
  '/login/recovery': typeof LoginRecoveryIndexRoute
  '/login/totp': typeof LoginTotpIndexRoute
  '/docs/emergency-info': typeof DashboardDocsEmergencyInfoIndexRoute
  '/docs/insights': typeof DashboardDocsInsightsIndexRoute
  '/docs/letters': typeof DashboardDocsLettersIndexRoute
  '/docs/life-check': typeof DashboardDocsLifeCheckIndexRoute
  '/docs/recovery': typeof DashboardDocsRecoveryIndexRoute
  '/docs/trusted-contacts': typeof DashboardDocsTrustedContactsIndexRoute
  '/docs/vault': typeof DashboardDocsVaultIndexRoute
  '/settings/contact': typeof DashboardSettingsContactIndexRoute
  '/settings/continuity': typeof DashboardSettingsContinuityIndexRoute
  '/settings/preferences': typeof DashboardSettingsPreferencesIndexRoute
  '/settings/recovery-kit': typeof DashboardSettingsRecoveryKitIndexRoute
  '/settings/security': typeof DashboardSettingsSecurityIndexRoute
  '/settings/subscription': typeof DashboardSettingsSubscriptionIndexRoute
  '/settings/usage': typeof DashboardSettingsUsageIndexRoute
  '/vault/$itemId': typeof DashboardVaultItemIdIndexRoute
  '/login/otp/recovery': typeof LoginOtpRecoveryIndexRoute
  '/login/totp/recovery': typeof LoginTotpRecoveryIndexRoute
  '/shared-with-me/$contactId/memorial': typeof DashboardSharedWithMeContactIdMemorialIndexRoute
  '/shared-with-me/$contactId/memorial/$itemId': typeof DashboardSharedWithMeContactIdMemorialItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/security/': typeof SecurityIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/_dashboard/docs/': typeof DashboardDocsIndexRoute
  '/_dashboard/hub/': typeof DashboardHubIndexRoute
  '/_dashboard/life-check/': typeof DashboardLifeCheckIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/shared-with-me/': typeof DashboardSharedWithMeIndexRoute
  '/_dashboard/terminate/': typeof DashboardTerminateIndexRoute
  '/_dashboard/trusted-contacts/': typeof DashboardTrustedContactsIndexRoute
  '/_dashboard/vault/': typeof DashboardVaultIndexRoute
  '/_onboarding/onboarding/': typeof OnboardingOnboardingIndexRoute
  '/invite/$token/': typeof InviteTokenIndexRoute
  '/life-check/confirm/': typeof LifeCheckConfirmIndexRoute
  '/login/otp/': typeof LoginOtpIndexRoute
  '/login/recovery/': typeof LoginRecoveryIndexRoute
  '/login/totp/': typeof LoginTotpIndexRoute
  '/_dashboard/docs/emergency-info/': typeof DashboardDocsEmergencyInfoIndexRoute
  '/_dashboard/docs/insights/': typeof DashboardDocsInsightsIndexRoute
  '/_dashboard/docs/letters/': typeof DashboardDocsLettersIndexRoute
  '/_dashboard/docs/life-check/': typeof DashboardDocsLifeCheckIndexRoute
  '/_dashboard/docs/recovery/': typeof DashboardDocsRecoveryIndexRoute
  '/_dashboard/docs/trusted-contacts/': typeof DashboardDocsTrustedContactsIndexRoute
  '/_dashboard/docs/vault/': typeof DashboardDocsVaultIndexRoute
  '/_dashboard/settings/contact/': typeof DashboardSettingsContactIndexRoute
  '/_dashboard/settings/continuity/': typeof DashboardSettingsContinuityIndexRoute
  '/_dashboard/settings/preferences/': typeof DashboardSettingsPreferencesIndexRoute
  '/_dashboard/settings/recovery-kit/': typeof DashboardSettingsRecoveryKitIndexRoute
  '/_dashboard/settings/security/': typeof DashboardSettingsSecurityIndexRoute
  '/_dashboard/settings/subscription/': typeof DashboardSettingsSubscriptionIndexRoute
  '/_dashboard/settings/usage/': typeof DashboardSettingsUsageIndexRoute
  '/_dashboard/vault/$itemId/': typeof DashboardVaultItemIdIndexRoute
  '/login/otp/recovery/': typeof LoginOtpRecoveryIndexRoute
  '/login/totp/recovery/': typeof LoginTotpRecoveryIndexRoute
  '/_dashboard/shared-with-me/$contactId/memorial/': typeof DashboardSharedWithMeContactIdMemorialIndexRoute
  '/_dashboard/shared-with-me/$contactId/memorial/$itemId/': typeof DashboardSharedWithMeContactIdMemorialItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/security/'
    | '/login/'
    | '/signup/'
    | '/docs/'
    | '/hub/'
    | '/life-check/'
    | '/settings/'
    | '/shared-with-me/'
    | '/terminate/'
    | '/trusted-contacts/'
    | '/vault/'
    | '/onboarding/'
    | '/invite/$token/'
    | '/life-check/confirm/'
    | '/login/otp/'
    | '/login/recovery/'
    | '/login/totp/'
    | '/docs/emergency-info/'
    | '/docs/insights/'
    | '/docs/letters/'
    | '/docs/life-check/'
    | '/docs/recovery/'
    | '/docs/trusted-contacts/'
    | '/docs/vault/'
    | '/settings/contact/'
    | '/settings/continuity/'
    | '/settings/preferences/'
    | '/settings/recovery-kit/'
    | '/settings/security/'
    | '/settings/subscription/'
    | '/settings/usage/'
    | '/vault/$itemId/'
    | '/login/otp/recovery/'
    | '/login/totp/recovery/'
    | '/shared-with-me/$contactId/memorial/'
    | '/shared-with-me/$contactId/memorial/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/security'
    | '/login'
    | '/signup'
    | '/docs'
    | '/hub'
    | '/life-check'
    | '/settings'
    | '/shared-with-me'
    | '/terminate'
    | '/trusted-contacts'
    | '/vault'
    | '/onboarding'
    | '/invite/$token'
    | '/life-check/confirm'
    | '/login/otp'
    | '/login/recovery'
    | '/login/totp'
    | '/docs/emergency-info'
    | '/docs/insights'
    | '/docs/letters'
    | '/docs/life-check'
    | '/docs/recovery'
    | '/docs/trusted-contacts'
    | '/docs/vault'
    | '/settings/contact'
    | '/settings/continuity'
    | '/settings/preferences'
    | '/settings/recovery-kit'
    | '/settings/security'
    | '/settings/subscription'
    | '/settings/usage'
    | '/vault/$itemId'
    | '/login/otp/recovery'
    | '/login/totp/recovery'
    | '/shared-with-me/$contactId/memorial'
    | '/shared-with-me/$contactId/memorial/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_onboarding'
    | '/_dashboard/settings'
    | '/security/'
    | '/_auth/login/'
    | '/_auth/signup/'
    | '/_dashboard/docs/'
    | '/_dashboard/hub/'
    | '/_dashboard/life-check/'
    | '/_dashboard/settings/'
    | '/_dashboard/shared-with-me/'
    | '/_dashboard/terminate/'
    | '/_dashboard/trusted-contacts/'
    | '/_dashboard/vault/'
    | '/_onboarding/onboarding/'
    | '/invite/$token/'
    | '/life-check/confirm/'
    | '/login/otp/'
    | '/login/recovery/'
    | '/login/totp/'
    | '/_dashboard/docs/emergency-info/'
    | '/_dashboard/docs/insights/'
    | '/_dashboard/docs/letters/'
    | '/_dashboard/docs/life-check/'
    | '/_dashboard/docs/recovery/'
    | '/_dashboard/docs/trusted-contacts/'
    | '/_dashboard/docs/vault/'
    | '/_dashboard/settings/contact/'
    | '/_dashboard/settings/continuity/'
    | '/_dashboard/settings/preferences/'
    | '/_dashboard/settings/recovery-kit/'
    | '/_dashboard/settings/security/'
    | '/_dashboard/settings/subscription/'
    | '/_dashboard/settings/usage/'
    | '/_dashboard/vault/$itemId/'
    | '/login/otp/recovery/'
    | '/login/totp/recovery/'
    | '/_dashboard/shared-with-me/$contactId/memorial/'
    | '/_dashboard/shared-with-me/$contactId/memorial/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SecurityIndexRoute: typeof SecurityIndexRoute
  InviteTokenIndexRoute: typeof InviteTokenIndexRoute
  LifeCheckConfirmIndexRoute: typeof LifeCheckConfirmIndexRoute
  LoginOtpIndexRoute: typeof LoginOtpIndexRoute
  LoginRecoveryIndexRoute: typeof LoginRecoveryIndexRoute
  LoginTotpIndexRoute: typeof LoginTotpIndexRoute
  LoginOtpRecoveryIndexRoute: typeof LoginOtpRecoveryIndexRoute
  LoginTotpRecoveryIndexRoute: typeof LoginTotpRecoveryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/login/totp/': {
      id: '/login/totp/'
      path: '/login/totp'
      fullPath: '/login/totp/'
      preLoaderRoute: typeof LoginTotpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/recovery/': {
      id: '/login/recovery/'
      path: '/login/recovery'
      fullPath: '/login/recovery/'
      preLoaderRoute: typeof LoginRecoveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/otp/': {
      id: '/login/otp/'
      path: '/login/otp'
      fullPath: '/login/otp/'
      preLoaderRoute: typeof LoginOtpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-check/confirm/': {
      id: '/life-check/confirm/'
      path: '/life-check/confirm'
      fullPath: '/life-check/confirm/'
      preLoaderRoute: typeof LifeCheckConfirmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token/': {
      id: '/invite/$token/'
      path: '/invite/$token'
      fullPath: '/invite/$token/'
      preLoaderRoute: typeof InviteTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/onboarding/': {
      id: '/_onboarding/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingOnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_dashboard/vault/': {
      id: '/_dashboard/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof DashboardVaultIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/trusted-contacts/': {
      id: '/_dashboard/trusted-contacts/'
      path: '/trusted-contacts'
      fullPath: '/trusted-contacts/'
      preLoaderRoute: typeof DashboardTrustedContactsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/terminate/': {
      id: '/_dashboard/terminate/'
      path: '/terminate'
      fullPath: '/terminate/'
      preLoaderRoute: typeof DashboardTerminateIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/shared-with-me/': {
      id: '/_dashboard/shared-with-me/'
      path: '/shared-with-me'
      fullPath: '/shared-with-me/'
      preLoaderRoute: typeof DashboardSharedWithMeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/life-check/': {
      id: '/_dashboard/life-check/'
      path: '/life-check'
      fullPath: '/life-check/'
      preLoaderRoute: typeof DashboardLifeCheckIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/hub/': {
      id: '/_dashboard/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof DashboardHubIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/': {
      id: '/_dashboard/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DashboardDocsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/login/totp/recovery/': {
      id: '/login/totp/recovery/'
      path: '/login/totp/recovery'
      fullPath: '/login/totp/recovery/'
      preLoaderRoute: typeof LoginTotpRecoveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/otp/recovery/': {
      id: '/login/otp/recovery/'
      path: '/login/otp/recovery'
      fullPath: '/login/otp/recovery/'
      preLoaderRoute: typeof LoginOtpRecoveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/vault/$itemId/': {
      id: '/_dashboard/vault/$itemId/'
      path: '/vault/$itemId'
      fullPath: '/vault/$itemId/'
      preLoaderRoute: typeof DashboardVaultItemIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/usage/': {
      id: '/_dashboard/settings/usage/'
      path: '/usage'
      fullPath: '/settings/usage/'
      preLoaderRoute: typeof DashboardSettingsUsageIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/subscription/': {
      id: '/_dashboard/settings/subscription/'
      path: '/subscription'
      fullPath: '/settings/subscription/'
      preLoaderRoute: typeof DashboardSettingsSubscriptionIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/security/': {
      id: '/_dashboard/settings/security/'
      path: '/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof DashboardSettingsSecurityIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/recovery-kit/': {
      id: '/_dashboard/settings/recovery-kit/'
      path: '/recovery-kit'
      fullPath: '/settings/recovery-kit/'
      preLoaderRoute: typeof DashboardSettingsRecoveryKitIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/preferences/': {
      id: '/_dashboard/settings/preferences/'
      path: '/preferences'
      fullPath: '/settings/preferences/'
      preLoaderRoute: typeof DashboardSettingsPreferencesIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/continuity/': {
      id: '/_dashboard/settings/continuity/'
      path: '/continuity'
      fullPath: '/settings/continuity/'
      preLoaderRoute: typeof DashboardSettingsContinuityIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/contact/': {
      id: '/_dashboard/settings/contact/'
      path: '/contact'
      fullPath: '/settings/contact/'
      preLoaderRoute: typeof DashboardSettingsContactIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/docs/vault/': {
      id: '/_dashboard/docs/vault/'
      path: '/docs/vault'
      fullPath: '/docs/vault/'
      preLoaderRoute: typeof DashboardDocsVaultIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/trusted-contacts/': {
      id: '/_dashboard/docs/trusted-contacts/'
      path: '/docs/trusted-contacts'
      fullPath: '/docs/trusted-contacts/'
      preLoaderRoute: typeof DashboardDocsTrustedContactsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/recovery/': {
      id: '/_dashboard/docs/recovery/'
      path: '/docs/recovery'
      fullPath: '/docs/recovery/'
      preLoaderRoute: typeof DashboardDocsRecoveryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/life-check/': {
      id: '/_dashboard/docs/life-check/'
      path: '/docs/life-check'
      fullPath: '/docs/life-check/'
      preLoaderRoute: typeof DashboardDocsLifeCheckIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/letters/': {
      id: '/_dashboard/docs/letters/'
      path: '/docs/letters'
      fullPath: '/docs/letters/'
      preLoaderRoute: typeof DashboardDocsLettersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/insights/': {
      id: '/_dashboard/docs/insights/'
      path: '/docs/insights'
      fullPath: '/docs/insights/'
      preLoaderRoute: typeof DashboardDocsInsightsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/emergency-info/': {
      id: '/_dashboard/docs/emergency-info/'
      path: '/docs/emergency-info'
      fullPath: '/docs/emergency-info/'
      preLoaderRoute: typeof DashboardDocsEmergencyInfoIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/shared-with-me/$contactId/memorial/': {
      id: '/_dashboard/shared-with-me/$contactId/memorial/'
      path: '/shared-with-me/$contactId/memorial'
      fullPath: '/shared-with-me/$contactId/memorial/'
      preLoaderRoute: typeof DashboardSharedWithMeContactIdMemorialIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/shared-with-me/$contactId/memorial/$itemId/': {
      id: '/_dashboard/shared-with-me/$contactId/memorial/$itemId/'
      path: '/shared-with-me/$contactId/memorial/$itemId'
      fullPath: '/shared-with-me/$contactId/memorial/$itemId/'
      preLoaderRoute: typeof DashboardSharedWithMeContactIdMemorialItemIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardSettingsContactIndexRoute: typeof DashboardSettingsContactIndexRoute
  DashboardSettingsContinuityIndexRoute: typeof DashboardSettingsContinuityIndexRoute
  DashboardSettingsPreferencesIndexRoute: typeof DashboardSettingsPreferencesIndexRoute
  DashboardSettingsRecoveryKitIndexRoute: typeof DashboardSettingsRecoveryKitIndexRoute
  DashboardSettingsSecurityIndexRoute: typeof DashboardSettingsSecurityIndexRoute
  DashboardSettingsSubscriptionIndexRoute: typeof DashboardSettingsSubscriptionIndexRoute
  DashboardSettingsUsageIndexRoute: typeof DashboardSettingsUsageIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardSettingsContactIndexRoute: DashboardSettingsContactIndexRoute,
  DashboardSettingsContinuityIndexRoute: DashboardSettingsContinuityIndexRoute,
  DashboardSettingsPreferencesIndexRoute:
    DashboardSettingsPreferencesIndexRoute,
  DashboardSettingsRecoveryKitIndexRoute:
    DashboardSettingsRecoveryKitIndexRoute,
  DashboardSettingsSecurityIndexRoute: DashboardSettingsSecurityIndexRoute,
  DashboardSettingsSubscriptionIndexRoute:
    DashboardSettingsSubscriptionIndexRoute,
  DashboardSettingsUsageIndexRoute: DashboardSettingsUsageIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardDocsIndexRoute: typeof DashboardDocsIndexRoute
  DashboardHubIndexRoute: typeof DashboardHubIndexRoute
  DashboardLifeCheckIndexRoute: typeof DashboardLifeCheckIndexRoute
  DashboardSharedWithMeIndexRoute: typeof DashboardSharedWithMeIndexRoute
  DashboardTerminateIndexRoute: typeof DashboardTerminateIndexRoute
  DashboardTrustedContactsIndexRoute: typeof DashboardTrustedContactsIndexRoute
  DashboardVaultIndexRoute: typeof DashboardVaultIndexRoute
  DashboardDocsEmergencyInfoIndexRoute: typeof DashboardDocsEmergencyInfoIndexRoute
  DashboardDocsInsightsIndexRoute: typeof DashboardDocsInsightsIndexRoute
  DashboardDocsLettersIndexRoute: typeof DashboardDocsLettersIndexRoute
  DashboardDocsLifeCheckIndexRoute: typeof DashboardDocsLifeCheckIndexRoute
  DashboardDocsRecoveryIndexRoute: typeof DashboardDocsRecoveryIndexRoute
  DashboardDocsTrustedContactsIndexRoute: typeof DashboardDocsTrustedContactsIndexRoute
  DashboardDocsVaultIndexRoute: typeof DashboardDocsVaultIndexRoute
  DashboardVaultItemIdIndexRoute: typeof DashboardVaultItemIdIndexRoute
  DashboardSharedWithMeContactIdMemorialIndexRoute: typeof DashboardSharedWithMeContactIdMemorialIndexRoute
  DashboardSharedWithMeContactIdMemorialItemIdIndexRoute: typeof DashboardSharedWithMeContactIdMemorialItemIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardDocsIndexRoute: DashboardDocsIndexRoute,
  DashboardHubIndexRoute: DashboardHubIndexRoute,
  DashboardLifeCheckIndexRoute: DashboardLifeCheckIndexRoute,
  DashboardSharedWithMeIndexRoute: DashboardSharedWithMeIndexRoute,
  DashboardTerminateIndexRoute: DashboardTerminateIndexRoute,
  DashboardTrustedContactsIndexRoute: DashboardTrustedContactsIndexRoute,
  DashboardVaultIndexRoute: DashboardVaultIndexRoute,
  DashboardDocsEmergencyInfoIndexRoute: DashboardDocsEmergencyInfoIndexRoute,
  DashboardDocsInsightsIndexRoute: DashboardDocsInsightsIndexRoute,
  DashboardDocsLettersIndexRoute: DashboardDocsLettersIndexRoute,
  DashboardDocsLifeCheckIndexRoute: DashboardDocsLifeCheckIndexRoute,
  DashboardDocsRecoveryIndexRoute: DashboardDocsRecoveryIndexRoute,
  DashboardDocsTrustedContactsIndexRoute:
    DashboardDocsTrustedContactsIndexRoute,
  DashboardDocsVaultIndexRoute: DashboardDocsVaultIndexRoute,
  DashboardVaultItemIdIndexRoute: DashboardVaultItemIdIndexRoute,
  DashboardSharedWithMeContactIdMemorialIndexRoute:
    DashboardSharedWithMeContactIdMemorialIndexRoute,
  DashboardSharedWithMeContactIdMemorialItemIdIndexRoute:
    DashboardSharedWithMeContactIdMemorialItemIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingOnboardingIndexRoute: typeof OnboardingOnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingOnboardingIndexRoute: OnboardingOnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SecurityIndexRoute: SecurityIndexRoute,
  InviteTokenIndexRoute: InviteTokenIndexRoute,
  LifeCheckConfirmIndexRoute: LifeCheckConfirmIndexRoute,
  LoginOtpIndexRoute: LoginOtpIndexRoute,
  LoginRecoveryIndexRoute: LoginRecoveryIndexRoute,
  LoginTotpIndexRoute: LoginTotpIndexRoute,
  LoginOtpRecoveryIndexRoute: LoginOtpRecoveryIndexRoute,
  LoginTotpRecoveryIndexRoute: LoginTotpRecoveryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
