// Shared env metadata for `check-env.mjs`, `check-convex-env.mjs`, and
// `sync-convex-env.mjs`. Single source of truth — edit here, never duplicate.

// Shared ANSI palette for all scripts/ — import these, never re-declare.
export const RED = "\x1b[31m";
export const YELLOW = "\x1b[33m";
export const GREEN = "\x1b[32m";
export const CYAN = "\x1b[36m";
export const DIM = "\x1b[2m";
export const BOLD = "\x1b[1m";
export const RESET = "\x1b[0m";

export const nonEmpty = (v) => typeof v === "string" && v.length > 0;
export const isHttpUrl = (v) => typeof v === "string" && /^https?:\/\//.test(v);
export const isNodeEnv = (v) =>
  ["development", "production", "test"].includes(v);
export const isConvexMode = (v) => ["cloud", "selfhosted"].includes(v);
export const isAuditSecret = (v) => {
  if (!nonEmpty(v) || v.startsWith("replace-me")) return false;
  try {
    return Buffer.from(v, "base64").length >= 32;
  } catch {
    return false;
  }
};

// Required by the Next.js process — loaded from `.env` / `.env.local`.
export const WEB_REQUIRED = [
  { key: "NEXT_PUBLIC_APP_URL", test: isHttpUrl },
  { key: "APP_URL", test: isHttpUrl },
  { key: "NODE_ENV", test: isNodeEnv },
  { key: "CONVEX_MODE", test: isConvexMode },
  {
    key: "CONVEX_DEPLOYMENT",
    test: nonEmpty,
    hint: "Run `npx convex dev --once --configure=new` first to create your deployment.",
  },
  { key: "NEXT_PUBLIC_CONVEX_URL", test: isHttpUrl },
  { key: "WEBAUTHN_RP_ID", test: nonEmpty },
  { key: "WEBAUTHN_RP_NAME", test: nonEmpty },
  { key: "WEBAUTHN_ORIGIN", test: isHttpUrl },
  {
    key: "KEEPLAS_CTX_SECRET",
    test: isAuditSecret,
    hint: "Generate with `openssl rand -base64 32` and push to Convex via `pnpm sync:convex-env`.",
  },
];

export const WEB_OPTIONAL_GROUPS = {
  "Email (Resend)": [
    "RESEND_API_KEY",
    "RESEND_FROM_EMAIL",
    "SUPPORT_INBOX_EMAIL",
  ],
  "Web Push (VAPID)": [
    "VAPID_PUBLIC_KEY",
    "VAPID_PRIVATE_KEY",
    "VAPID_SUBJECT",
    "NEXT_PUBLIC_VAPID_PUBLIC_KEY",
  ],
  "WhatsApp (Infobip)": [
    "INFOBIP_BASE_URL",
    "INFOBIP_API_KEY",
    "INFOBIP_WHATSAPP_SENDER",
  ],
};

// Required on the Convex deployment — read at action/mutation time on the
// server. `mustMatchLocal: true` means the Convex value must equal the local
// `.env.local` value (HMAC roundtrip would otherwise fail).
const JWT_BOOTSTRAP_HINT =
  "Auto-generated by Better Auth on first sign-in. Run `npx convex dev` and sign in via the app once, then re-run.";

export const CONVEX_REQUIRED = [
  {
    key: "KEEPLAS_CTX_SECRET",
    test: isAuditSecret,
    mustMatchLocal: true,
  },
  { key: "RESEND_API_KEY", test: nonEmpty },
  { key: "RESEND_FROM_EMAIL", test: nonEmpty },
  { key: "APP_URL", test: isHttpUrl },
  { key: "SITE_URL", test: isHttpUrl },
  { key: "WEBAUTHN_RP_ID", test: nonEmpty },
  { key: "WEBAUTHN_RP_NAME", test: nonEmpty },
  { key: "WEBAUTHN_ORIGIN", test: isHttpUrl },
  { key: "JWKS", test: nonEmpty, hint: JWT_BOOTSTRAP_HINT },
  { key: "JWT_PRIVATE_KEY", test: nonEmpty, hint: JWT_BOOTSTRAP_HINT },
];

export const CONVEX_OPTIONAL_GROUPS = {
  "Support inbox (Resend)": ["SUPPORT_INBOX_EMAIL"],
  "Web Push (VAPID)": [
    "VAPID_PUBLIC_KEY",
    "VAPID_PRIVATE_KEY",
    "VAPID_SUBJECT",
  ],
  "WhatsApp (Infobip)": [
    "INFOBIP_BASE_URL",
    "INFOBIP_API_KEY",
    "INFOBIP_WHATSAPP_SENDER",
    "WHATSAPP_TEMPLATE_NAME",
    "WHATSAPP_TEMPLATE_LANG",
  ],
};

// Keys pushed by `sync-convex-env.mjs` from local env files to Convex.
// JWKS / JWT_PRIVATE_KEY are excluded — Better Auth manages them on the
// deployment side; trying to overwrite them would invalidate existing sessions.
export const CONVEX_SYNC_KEYS = [
  "KEEPLAS_CTX_SECRET",
  "WEBAUTHN_RP_ID",
  "WEBAUTHN_RP_NAME",
  "WEBAUTHN_ORIGIN",
  "APP_URL",
  "SITE_URL",
  "RESEND_API_KEY",
  "RESEND_FROM_EMAIL",
  "SUPPORT_INBOX_EMAIL",
  "VAPID_PUBLIC_KEY",
  "VAPID_PRIVATE_KEY",
  "VAPID_SUBJECT",
  "INFOBIP_BASE_URL",
  "INFOBIP_API_KEY",
  "INFOBIP_WHATSAPP_SENDER",
  "WHATSAPP_TEMPLATE_NAME",
  "WHATSAPP_TEMPLATE_LANG",
];

// Subset of CONVEX_SYNC_KEYS that MUST have a non-empty local value when syncing
// (sync fails loudly if any of these is empty in `.env` / `.env.local` /
// `.env.convex.local`). JWKS / JWT_PRIVATE_KEY excluded — see above.
export const CONVEX_SYNC_REQUIRED_KEYS = CONVEX_REQUIRED.filter(
  ({ key }) => key !== "JWKS" && key !== "JWT_PRIVATE_KEY",
).map(({ key }) => key);
