import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  buildContentSecurityPolicy,
  buildSecurityHeaders,
} from "./security-headers";

const HASH = "'sha256-AbC123='";

describe("buildContentSecurityPolicy", () => {
  const originalConvexUrl = process.env.NEXT_PUBLIC_CONVEX_URL;

  beforeEach(() => {
    delete process.env.NEXT_PUBLIC_CONVEX_URL;
  });

  afterEach(() => {
    if (originalConvexUrl === undefined) {
      delete process.env.NEXT_PUBLIC_CONVEX_URL;
    } else {
      process.env.NEXT_PUBLIC_CONVEX_URL = originalConvexUrl;
    }
  });

  it("allow-lists inline scripts by their SHA-256 hash in script-src", () => {
    const csp = buildContentSecurityPolicy([HASH]);
    expect(csp).toMatch(new RegExp(`script-src [^;]*${HASH}`));
  });

  it("allow-lists inline script elements by their SHA-256 hash", () => {
    const csp = buildContentSecurityPolicy([HASH]);
    expect(csp).toMatch(new RegExp(`script-src-elem [^;]*${HASH}`));
  });

  it("allow-lists script elements by nonce in production", () => {
    const csp = buildContentSecurityPolicy([], ["abc123"]);
    expect(csp).toMatch(/script-src [^;]*'nonce-abc123'/);
    expect(csp).toMatch(/script-src-elem [^;]*'nonce-abc123'/);
  });

  it("serves bundled scripts from same-origin via 'self'", () => {
    const csp = buildContentSecurityPolicy([]);
    expect(csp).toMatch(/script-src [^;]*'self'/);
  });

  it("allows WASM execution required by hash-wasm (Argon2id)", () => {
    const csp = buildContentSecurityPolicy([HASH]);
    expect(csp).toContain("'wasm-unsafe-eval'");
    expect(csp).toMatch(/worker-src [^;]*blob:/);
  });

  it("locks down dangerous directives", () => {
    const csp = buildContentSecurityPolicy([HASH]);
    expect(csp).toContain("default-src 'self'");
    expect(csp).toContain("object-src 'none'");
    expect(csp).toContain("base-uri 'none'");
    expect(csp).toContain("frame-ancestors 'none'");
    expect(csp).toContain("form-action 'self'");
  });

  it("never permits unsafe-eval in production (only the scoped wasm variant)", () => {
    const original = process.env.NODE_ENV;
    vi.stubEnv("NODE_ENV", "production");
    try {
      const csp = buildContentSecurityPolicy([HASH]);
      expect(csp).toContain("'wasm-unsafe-eval'");
      // The standalone token never appears (the wasm-scoped variant does not
      // contain a leading-quote "'unsafe-eval'").
      expect(csp).not.toContain("'unsafe-eval'");
    } finally {
      vi.stubEnv("NODE_ENV", original ?? "test");
    }
  });

  it("permits unsafe-eval in development (React dev build needs eval)", () => {
    const original = process.env.NODE_ENV;
    vi.stubEnv("NODE_ENV", "development");
    try {
      const csp = buildContentSecurityPolicy([HASH]);
      expect(csp).toMatch(/script-src [^;]*'unsafe-eval'/);
    } finally {
      vi.stubEnv("NODE_ENV", original ?? "test");
    }
  });

  it("always scopes connect-src to the Convex wildcard hosts", () => {
    const csp = buildContentSecurityPolicy([HASH]);
    expect(csp).toContain("https://*.convex.cloud");
    expect(csp).toContain("wss://*.convex.cloud");
  });

  it("allows data URL fonts generated by Vite asset inlining", () => {
    const csp = buildContentSecurityPolicy([HASH]);
    expect(csp).toMatch(/font-src [^;]*data:/);
  });

  it("adds the configured Convex origin to connect-src when present", () => {
    process.env.NEXT_PUBLIC_CONVEX_URL =
      "https://energetic-pony-179.convex.cloud";
    const csp = buildContentSecurityPolicy([HASH]);
    expect(csp).toContain("https://energetic-pony-179.convex.cloud");
  });

  it("ignores a malformed Convex URL without throwing", () => {
    process.env.NEXT_PUBLIC_CONVEX_URL = "not a url";
    expect(() => buildContentSecurityPolicy([HASH])).not.toThrow();
    const csp = buildContentSecurityPolicy([HASH]);
    expect(csp).toContain("https://*.convex.cloud");
  });
});

describe("buildSecurityHeaders", () => {
  it("returns the CSP plus all hardening headers", () => {
    const headers = buildSecurityHeaders([HASH]);
    expect(headers["Content-Security-Policy"]).toContain(HASH);
    expect(headers["X-Content-Type-Options"]).toBe("nosniff");
    expect(headers["Referrer-Policy"]).toBe("no-referrer");
    expect(headers["Strict-Transport-Security"]).toBe(
      "max-age=63072000; includeSubDomains; preload",
    );
    expect(headers["X-Frame-Options"]).toBe("DENY");
  });

  it("disables sensitive features but keeps WebAuthn get + same-origin media", () => {
    const headers = buildSecurityHeaders([HASH]);
    const policy = headers["Permissions-Policy"];
    expect(policy).toContain("camera=(self)");
    expect(policy).toContain("microphone=(self)");
    expect(policy).toContain("geolocation=()");
    expect(policy).toContain("publickey-credentials-get=(self)");
  });
});
